name: Build and Test

on:
  push:
    tags-ignore:
      - '*.*'
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.4' # The Go version to download (if necessary) and use.
    - name: Test
      run: |
        make test
